### ISSUE TITLE
Getting an Invalid Parameter object error during document creation

### ISSUE THREAD

**Issue by adecruz-avg** [johannschopplich/pdfjs-serverless#2]
I'm currently doing this to retrieve a PDF, and add it to the document. This is with Supabase Edge Functions.

`const response = await fetch(
        url,
        {
            headers: {
                "content-type": "application/pdf",
            },
            method: "GET",
        },
    );
    const responseBuffer = await response.arrayBuffer();
   
    const { getDocument } = await resolvePDFJS()
    const doc = await getDocument({
        responseBuffer
    }).promise`

The URL is correct, and fetches the PDF, and casts it to a buffer.

However when the getDocument is called, this error appears.

Error: Invalid parameter object: need either .data, .range or .url
    at rt (https://esm.sh/v133/pdfjs-serverless@0.4.0/deno/pdfjs-serverless.mjs:60:26701)

**Comment by johannschopplich** [comment]
Seems like you're passing `responseBuffer` to the `getDocument` function. But this isn't a valid parameter.

Instead, use:
```ts
await getDocument(responseBuffer).promise
// or
await getDocument({ data: responseBuffer }).promise
```
